### ISSUE TITLE
Some Recipes Do Not Use OreDictionary

### ISSUE THREAD

**Issue by Darkosto** [pau101/Fairy-Lights#10]
Hello!

I'm working on a modpack and noticed the Jack-O-Lantern light recipes do not use Ore-Dictionaried wooden slabs. Is this intended? If not, could it be possible to ore dictionary them? 

FairyLights: 2.0.5
MC: 1.10.2
Forge: 2209

I love the mod so far! It looks really cool, and thank you for making those server fixes/updates!
Darkosto

**Comment by pau101** [comment]
It is intended that the crafting recipe uses only Acacia slabs because they follow the theme of pumpkins being orange. Although, I'm fine with changing it to be any wooden slab so they can be crafted easier.

**Comment by Darkosto** [comment]
Okay! Sounds good :) Thanks for the response. Acacia sounds good :)

**Comment by pau101** [comment]
Requiring Acacia because pumpkins are orange isn't much of a logical reason thinking back since the light is colored whatever of the dye is so I've gone with any wooden slab.
