### ISSUE TITLE
color does not change if letter bunting is used if the first letter is already painted

### ISSUE THREAD

**Issue by D4NICKY** [pau101/Fairy-Lights#100]
I think this is due to the fact that the paragraph mark does not work since version 1.13. but if you manually do the text formatting, then the multi-colored text works.

**Comment by pau101** [comment]
The text styling works by the color being what is used to type, or if you make a selection the styling can be changed at once.

**Comment by D4NICKY** [comment]
in version 1.12.2 I could make colored letters, in version 1.16.4 nothing is written when changing colors.

**Comment by D4NICKY** [comment]
but I still can't make blinking garlands due to the fact that glow stone dust has been changed in the new version of minecraft

**Comment by pau101** [comment]
Letter bunting text editing works as intended for me and creating blinking lights was changed to glowstone being added to the light in the crafting table individually and then using it to craft a stand like normal.
