### ISSUE TITLE
vanishing Fairy Lights

### ISSUE THREAD

**Issue by Entchenbrot** [pau101/Fairy-Lights#101]
Hi, playing the mod on 1.12.2 with loads of other mods

I recently realised that at some points the lights will just vanish

the little grey blocks they're attached to are still there and also the hitbox is visible, but the lights themselves just disappear

currently its just about some fairy lights and its always the same place were they vanish after reconnecting

is there a way to fix that? i can't figure out why they vanish because any fairy light that vanishes is in a different position with different blocks and there are lights in similar positions which wont disappear so i dont know whats happening

thanks for helping!

**Comment by pau101** [comment]
Fairy Lights for 1.12 is no longer supported unfortunately, be sure you are on the latest version at least.
