### ISSUE TITLE
[1.12.2] server crash when holding letter bunting in hand

### ISSUE THREAD

**Issue by xemnes** [pau101/Fairy-Lights#102]
when i created letter bunting then held it in the hand, the server crashed. 
heres the crash report:
https://gist.github.com/xemnes/0ea08bc38ee155d6cb942ebb89dce975

looks like it might have something to do with laggoggles.

**Comment by pau101** [comment]
Yes that may be possible, I suspect it is performing reflective class loading and a pair of classes in Fairy Lights depend on correct order. No fix will be done on my end as 1.12 is no longer supported and the issue no longer exists post 1.12 due to internal refactoring.
