### ISSUE TITLE
Recipe Bug

### ISSUE THREAD

**Issue by ladiesman4217** [pau101/Fairy-Lights#104]
When crafting a fairy light the recipe will stop working and output nothing.
![2020-12-29_16 47 41](https://user-images.githubusercontent.com/8000380/103323068-08999f00-49f6-11eb-9070-e5f1f710310d.png)
These screenshots were taken a few seconds apart, all I did to make it happen was pick up the dye and place it back down.
![2020-12-29_16 47 53](https://user-images.githubusercontent.com/8000380/103323098-1b13d880-49f6-11eb-9402-904142874f43.png)

Minecraft version 1.16.4
Forge version 35.1.11
FairyLights version 4.0.4

**Comment by pau101** [comment]
Duplicates #95
