### ISSUE TITLE
MultMC issue: Recursive crafting of fairy lights causes a crash

### ISSUE THREAD

**Issue by RowannWilder** [pau101/Fairy-Lights#105]
Black paper lanterns placed in a pattern similar pattern to flint and steel (2x2 grid, with black lanterns in each corner) is considered a valid recipe for crafting more black paper lanterns. This allows duplication in survival. The glitch also lead to a silent game crash (log stops prematurely) while connected to a server. Game version is 1.16.4, attached is a screenshot of crafting recipe.

![image](https://user-images.githubusercontent.com/76808061/103401974-fc016d80-4aff-11eb-877b-a65a4f0bcf6e.png)

**Comment by pau101** [comment]
Thanks for reporting!

Appears I'm neglecting to set the result stack size to 1 from the input ingredient, where this recipe is intended for mixing custom colors of lights. Fix will be soon!

**Comment by RowannW** [comment]
Good catch, I wasn't sure where it was coming from, was definitely curious.

**Comment by pau101** [comment]
Fixed in [Release 4.0.5](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3216206)
