### ISSUE TITLE
Recipes arent shown in JEI [1.16.4]

### ISSUE THREAD

**Issue by SugarDaddii** [pau101/Fairy-Lights#106]
Forge Build: 1.16.4-35.1.28
Fairy Lights : fairylights-4.0.4-1.16.4.jar
JEI : jei-1.16.4-7.6.1.65.jar

When i Join Server i cant click on any recipes for fairy lights!
After /reload all is shown correctly! When when i reconnect its the same again!
Also for my players its the same and always someone new is joining i need to /reload it!
Is there a way around this?

Have a nice day!

**Comment by guitaristtom** [comment]
I have this problem as well, and I'm running Valhelsia 3 v3.1.2

**Comment by werderengineering** [comment]
Also have this issue. Also if you make a fairy light it brings up the recipes have been added to the book notification, but then never adds them and the notification doesn't disappear.

**Comment by pau101** [comment]
This is currently a limitation of JEI supporting certain kinds of custom recipes. I have spoken with the developer on this and nothing is in the works yet.

@werderengineering that toast you see is a tutorial toast that shows up once lights are collected and remains until fairy lights are crafted and hidden if lights are taken out of the inventory.

**Comment by pau101** [comment]
Duplicates #95
