### ISSUE TITLE
Can't place second point of Hanging Lights

### ISSUE THREAD

**Issue by harrislapiroff** [pau101/Fairy-Lights#107]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2854
Fairy Lights Version: 2.2.0

Letter bunting seems to work fine, but hanging lights do not. They just stay stuck to me even when I try to place them.

**Comment by pau101** [comment]
The 1.12 releases of Fairy Lights are not longer supported, however I can suggest this is likely an incompatibility with another mod. Are you able to reproduce this issue with only Fairy Lights installed?

**Comment by harrislapiroff** [comment]
I'll give it a try. Here's the list of mods I have installed, in case there's any known incompatibilities you can tell me about. Bummer about 1.12 support, but I get it.


    ☃ Snow! Real Magic! (by Snownee_)
    Dynamic Trees - Quark (by supermassimo0310)
    Chunk Animator (by Lumien231)
    Biomes O' Plenty (by Forstride)
    Future MC (by thedarkcolour)
    Fairy Lights (by pau101)
    Emojicord (by Kamesuta)
    Wawla - What Are We Looking At (by DarkhaxDev)
    GraveStone Mod (by henkelmax)
    Dynamic Trees - Biomes O' Plenty Compat (by cadaverous_queen)
    Defiled Lands (by Lykrast)
    Ender Crop (by DrManganese)
    Dynamic Trees (by ferreusveritas)
    Roguelike Dungeons (by Greymerk)
    Mystcraft (by XCompWiz)
    AutoRegLib (by Vazkii)
    Serene Seasons (by TheAdubbz)
    Shadowfacts' Forgelin (by ShadowfactsDev)
    Charm (by svenhjol)
    Baubles (by Azanor13)
    Ender Mail (by Chaosyr)
    JourneyMap (by techbrew)
    Rope Bridge (by lordcazsius)
    Quark (by Vazkii)
    Ice and Fire: Dragons (by alex1the1666)
    Dynamic Surroundings (by OreCruncher)
    OreLib (by OreCruncher)
    Waystones (by BlayTheNinth)
    Recurrent Complex (by Ivorforce)
    Just Enough Items (JEI) (by mezz)
    [Backport] 1.13 Water Mechanics [Bubble Columns] (by xFrah)
    OpenBlocks Elevator (by vsngarcia)
    LLibrary (by _ForgeUser11902522)
    IvToolkit (by Ivorforce)
    Bloodmoon (by Lumien231)
    Sign Button (by gigaherz)
    Hwyla (by TehNut)

**Comment by harrislapiroff** [comment]
Scratch the previous comment: I have confirmed I can reproduce it with no other mods installed on a fresh Minecraft profile.

**Comment by harrislapiroff** [comment]
Never mind, I figured it out! I was testing with `/give <user> fairylights:hanging_lights`, which I guess gives me lights without a valid color, which are thus unplacable. Crafted lights seem to work fine. Closing.

**Comment by pau101** [comment]
Yep that would do it, glad it got sorted!
