### ISSUE TITLE
Recipes Show as invalid with Refined Storage

### ISSUE THREAD

**Issue by guitaristtom** [pau101/Fairy-Lights#109]
Using Valhelsia 3 the recipes are sporadic on if they work or not at all, but especially with Refined Storage.

If you need more specifics for the versions, I can provide more.

![image](https://user-images.githubusercontent.com/6890628/103871236-a7bb3800-5081-11eb-97f7-acada6285f16.png)
![image](https://user-images.githubusercontent.com/6890628/103871246-ab4ebf00-5081-11eb-946a-6dfbe801bb77.png)

**Comment by pau101** [comment]
Duplicates #95
