### ISSUE TITLE
Letter bunting cannot be placed in 1.16.4

### ISSUE THREAD

**Issue by lolabirde** [pau101/Fairy-Lights#110]
it has a quick flash but but does not place. Ends up back in hand.

**Comment by StokedTheorem** [comment]
I am having this same issue

**Comment by voodoofrog** [comment]
As am I.

**Comment by pau101** [comment]
Closing as should be a duplicate of #110

**Comment by jexom** [comment]
Having ther same problem in 1.16.5. You just closed the issue because it's a duplicate of itself
