### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WenXin20** [pau101/Fairy-Lights#111]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Fairy Lights v4.0.4`

I was on my server testing some machine blocks from [Tofucraft](https://www.curseforge.com/minecraft/mc-mods/tofucraftreload) when I suddenly crashed client-side. I hadn't placed any fairy lights.
[Crash Report](https://gist.github.com/WenXin20/78bf992ccc278817888a286be8c1ace4)

**Comment by pau101** [comment]
Thanks for reporting! Unfortunately this is an issue on Tofucraft's end, as it appears they have wrongly implement block capabilities.

**Comment by WenXin20** [comment]
Oh oof. I'll report it to them.
