### ISSUE TITLE
Recipes do not appear in JEI

### ISSUE THREAD

**Issue by miiichael** [pau101/Fairy-Lights#115]
Recipes do not appear in JEI. I can provide logs, but they do not seem to hint at any fairy light problems...

**Comment by pau101** [comment]
Are you using 1.1?, If so update JEI, otherwise you're out of luck unfortunately.

**Comment by khazenor** [comment]
Try testing it on a server?  I realized that for me the recipe doesn't show up in a server environment in my modpack.  I haven't done testing in a isolated environment though.  

environment with recipes missing on a server:
 - fairylights-4.0.5-1.16.5
 - forge 1.16.4: 35.1.36
 - jei-1.16.4-7.6.0.62
 
 environment with recipes not missing on a server:
 - fairylights-4.0.4-1.16.4
 - forge 1.16.4: 35.1.36
 - jei-1.16.4-7.6.0.62

**Comment by pau101** [comment]
Yes this is server specific issue. JEI at minimum 1.16.4-7.6.1.68 is needed, as that is when the issue was resolved on their end.

Closing as nothing to do on my part.

**Comment by miiichael** [comment]
\*goes to report a bug against JEI in-game update checking being broken. :sweat_smile::sweat_smile::sweat_smile:*

![image](https://user-images.githubusercontent.com/4179353/111089625-97cf4100-8567-11eb-8e50-38320799a928.png)
