### ISSUE TITLE
Question regarding older version

### ISSUE THREAD

**Issue by xJon** [pau101/Fairy-Lights#118]
Hi,
Does the 1.7.10 version of the mod suppose to have any recipe integration with NEI?
It seems impossible to get any in-game recipe indication for any item the mod adds (even though the recipes do seem to work), but I might be missing something?
Thanks!

**Comment by pau101** [comment]
No it does not. You will need to play on modern versions of the mod for such features with JEI integration.

**Comment by xJon** [comment]
@pau101 Is the older version also covered by the MIT license? (asking in order to resolve this issue). Thanks!
