### ISSUE TITLE
Meteor lights turn black when turned on when using BSL shaders

### ISSUE THREAD

**Issue by lucifer7303** [pau101/Fairy-Lights#120]
All other lights work fine except meteor lights
When I just place the block it looks fine but just after a split second it goes black..when turned on the light is black and when turned off its just very dull of that version.
Video:https://cdn.discordapp.com/attachments/603483996910780426/839545822802214922/Minecraft__1.16.5_-_Singleplayer_2021-05-05_22-24-28.mp4

**Comment by pau101** [comment]
Sadly not everything will work with every shader.
