### ISSUE TITLE
Block Id's

### ISSUE THREAD

**Issue by Austjonez** [pau101/Fairy-Lights#122]
I'm currently messing around and trying to get these lights to work in SEUS PTGI by editing the block.properties file. For some reason, the block id's aren't working for it. I've had success with other mods but copying the block id and adding it to the list seems to not do anything. I realize this might be out of your area so any help is appreciated.

**Comment by CeagleMan** [comment]
I'm trying to achieve the same thing and also happened to run into the same problem. I RECKON that the problem is that each individual string of lights have a few NBT's and as far as I'm concerned you can't add blocks with NBT's to the block.properties file?

**Comment by Austjonez** [comment]
Glad to know I'm not the only one trying this! I'll keep attempting things and I'll let you know if there is any progress. I wonder if it would be possible (and not too much work) to convert the lights into normal blocks that don't contain any NBT data if that's what's needed? And speaking of blocks with NBT data, campfires can have nbt data and still emit a light source even though it isn't explicitly mentioned in the block.properties file. Since the base block is mentioned in the file, it emits light. Also, lights like the incandescent light do not have any NBT tags and they also do not work.

**Comment by CeagleMan** [comment]
I dug a little deeper and I think we can't do much about making these lights work with SEUS PTGI is because the lights are entities and as far as I'm concerned you can't add entities to the block.properties? Could be very wrong though

**Comment by pau101** [comment]
The hanging lights require unique rendering and likely cannot integrate unfortunately.
