### ISSUE TITLE
Version 4.0.5 [MC 1.16.5] disables spawning of squid

### ISSUE THREAD

**Issue by Der-Fuzzi** [pau101/Fairy-Lights#123]
After a lot of swimming around looking for squid, I have given up and tested around which mod was affecting it...
It turns out, that Fairy-Lights seems to disable the natural spawning of vanilla squid completely.

Haven't noticed any other entities missing

-Fuzzi

**Comment by pau101** [comment]
Pardon my late reply, but have you tested without fairy lights?

**Comment by Der-Fuzzi** [comment]
I definitely checked that last time and it was working without fairy lights,
but just now, fairy lights wasn't the problem and something else seems to cause the issue.
I could have sworn I tested everything last time, but we've also upgraded some mods since then, so idk...
I'm confused now
