### ISSUE TITLE
1.19 language error 

### ISSUE THREAD

**Issue by pudd1esexe** [pau101/Fairy-Lights#146]
pls make other 1.19 versions other 1.19.2 as it does not work on older 1.19 versions

**Comment by pudd1esexe** [comment]
[latest.log](https://github.com/pau101/Fairy-Lights/files/10146150/latest.log)

**Comment by mintynora** [comment]
That's not a language error, you're trying to use a mod for a version it wasn't made for.

Just play 1.19.2. it's more stable as well as having more mods on it. Chat reporting is easy to get rid of, so there's no reason at all to keep playing a discontinued version.

**Comment by pudd1esexe** [comment]
> That's not a language error, you're trying to use a mod for a version it wasn't made for.
> 
> Just play 1.19.2. it's more stable as well as having more mods on it. Chat reporting is easy to get rid of, so there's no reason at all to keep playing a discontinued version.

based on the fact it said "language error" I 100% believe its a language error, yes I know its because it's not the exact version but due to the fact most mods will still be compatible with other mods that are different snapshots within the same version and that the current mod pack I play with all my friends is 1.19 because 90% of the mods on it are on 1.19 and not 1.19.2 I don't really think it's fair to say "just play 1.19.2" and completely skip the main version and only doing 1.19.2

**Comment by mintynora** [comment]
I really couldn't care less about the modpack you play with your friends. Don't play a discontinued, unsupported version if you don't want things to break.
