### ISSUE TITLE
Show Hanging Light Item in JEI

### ISSUE THREAD

**Issue by Voidi** [pau101/Fairy-Lights#15]
It would be useful to show one Hanging Light Item in the JEI item list and cycle through all recipe variants in the recipe view.

**Comment by pau101** [comment]
There are over 2 trillion variants, so I'll cycle through some preselected examples.

**Comment by pau101** [comment]
[Fairy Lights 2.1.0](https://minecraft.curseforge.com/projects/fairy-lights/files) is now out to implement this feature.
