### ISSUE TITLE
Cannot remove step-ladder

### ISSUE THREAD

**Issue by bryanpalmer** [pau101/Fairy-Lights#17]
Fairy lights is in the skyfactory 3 mod pack.  I created a stepladder, and placed it down in the middle of my base, and nothing I do will remove it.  I've tried weapons, picks, axes, clicking with empty hands, shift clicking, etc.

How does one remove or pick up a placed stepladder?

**Comment by pau101** [comment]
Hit it twice in quick succession. It has the same breaking mechanic as armorstands.
