### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Rikki21** [pau101/Fairy-Lights#18]
I'm not 100% sure if this has to do with Fairy Lights, but the crash report only mentions it? However, I'm not really great at reading crash reports so.

I have a couple skull fairy lights hanging up in the Sky Factory 3 modpack (3.0.6, MC ver 1.10.2). I recently put in a couple of pedestals for Draconic Evolutions dislocators. I teleported in the same dimension about 100-200 blocks away 3 times and back home (where the lights are hanging) with no problems. Upon teleporting back home the 4th time, I crashed and received [this crash report.](http://pastebin.com/k6aMAzCA)  ([crash-2017-02-17_02.13.56-client.txt](https://github.com/pau101/Fairy-Lights/files/782773/crash-2017-02-17_02.13.56-client.txt))

Like I said, the crash report mentioned Fairy Lights, so I'm posting it here for your perusal. 

Let me know if it's another mod causing the problems so I can post the report for them. 

Edit: Not a one time thing, it happened again after a few okay teleports.

**Comment by pau101** [comment]
The next release will have the fix.

**Comment by pau101** [comment]
[Fairy Lights 2.1.0](https://minecraft.curseforge.com/projects/fairy-lights/files) is now out to resolve this issue.
