### ISSUE TITLE
Crossroads crash

### ISSUE THREAD

**Issue by JinxSwift** [pau101/Fairy-Lights#19]
Placing fluid cooler from crossroads caused this http://pastebin.com/TU0ysvKx

Edit: This is only a client side crash. SMP server is fine

**Comment by pau101** [comment]
This is a problem on Crossroads part, so hopefully it is resolved soon.

**Comment by pau101** [comment]
[Crossroads 1.3.7](https://minecraft.curseforge.com/projects/crossroads-mc/files/2385874) has been released to fix this bug.
