### ISSUE TITLE
[SF3] Can't attach lights?

### ISSUE THREAD

**Issue by Lethann** [pau101/Fairy-Lights#20]
Not sure if this is only on my Sky Factory 3.0.6 server or not. For some odd reason when I right click with a light in my hand nothing happens. I've tried repeatedly right clicking various points, shift right clicking, removing armor, trying a couple types, nothing.  Tried changing what I'm trying to attach it to (basic cobble!) but still nothing.

Skyfactory 3.0.6
Fairy Lights 2.0.6

**Comment by pau101** [comment]
Lights don't attach by themselves, they are used to craft hanging lights. Here are some example recipes:
![Recipes](https://i.imgur.com/GcbQI0D.png)

**Comment by Lethann** [comment]
*feels like a total idiot*

You know, I read and read and read the page but for some reason it just never clicked.
