### ISSUE TITLE
Update zh_CN

### ISSUE THREAD

**Issue by pau101** [pau101/Fairy-Lights#21]
There are a [couple new subtitles](https://github.com/pau101/Fairy-Lights/commit/4edeba09425c0e96643d7c249f1638bbc176bb4e#diff-b152e2a3ba01aaed497bcb35ce79498f) which need Chinese localization, as apart of the new feature of hanging lights emitting true light. @TartaricAcid, I would be grateful for your assistance.

**Comment by TartaricAcid** [comment]
Thank you for reminding me.
