### ISSUE TITLE
[1.10.2] Lights dupe when you right click the garland/string with another one.

### ISSUE THREAD

**Issue by JAWSAWN** [pau101/Fairy-Lights#24]
Steps to Reproduce:

1-Place a garland/light
2-Right click the placed garland/light with the same item, not the ends but the garland itself. 
3-It gives you an extra garland when you do that, so a dupe bug.

**Comment by pau101** [comment]
Thanks for reporting! An update will be released in a couple days.

**Comment by pau101** [comment]
[Update released](https://minecraft.curseforge.com/projects/fairy-lights/files/2459418)
