### ISSUE TITLE
Transparency punch-through

### ISSUE THREAD

**Issue by ouroborus** [pau101/Fairy-Lights#27]
In the two screenshots, one has transparency punch-through and the other doesn't. Whether this happens or not depends on the angle you view the lights at.

(This might be an issue with just Colassal Chests.)

![2017-10-30_18 11 06](https://user-images.githubusercontent.com/392047/32203006-df76b38e-bd9d-11e7-8ac2-d221a409a07f.png)
![2017-10-30_18 11 17](https://user-images.githubusercontent.com/392047/32203007-df8ef282-bd9d-11e7-8cf2-47b10686410d.png)

**Comment by pau101** [comment]
This is the expected behavior, there isn't a solution that a single mod can implement.
