### ISSUE TITLE
Various lights won't place in the world

### ISSUE THREAD

**Issue by armuell** [pau101/Fairy-Lights#29]
Both the red hanging lights and the red paper lanterns (and probably quite a few more, I didn't check them all) will not place in the world. I believe various lights in the mod are not placing on the side of blocks for unknown reasons.

**Comment by ouroborus** [comment]
@armuell All the lights/lanterns needs to crafted into "hanging lights" in order to be placed.

**Comment by pau101** [comment]
ouroborus is correct, after making colored lights you use them in the hanging lights recipe which provides a placeable item. Here are some example usages:

![hanging lights crafting recipes](http://i.imgur.com/GcbQI0D.png)

**Comment by armuell** [comment]
Wow I'm dumb, thank you for the clarification!
