### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Matthysse** [pau101/Fairy-Lights#30]
Hello, (sorry for my bad english i'm french)

Yes, i know that 1.7.10 version is no more supported, but PLEASE just release a new version JUST for the issue with Optifine E3, i realy need this mod, and the last version of optifine include shaders(and more optimisation), so that i don't need a shader mod. You would be really nice to do that, just that, please.
(The crash report is already on an other post "1.7.10 crash")

**Comment by pau101** [comment]
There will not be any new releases for 1.7.10 because it is unsupported.
