### ISSUE TITLE
Ability to change cable color?

### ISSUE THREAD

**Issue by ouroborus** [pau101/Fairy-Lights#31]
I'd like to be able to change the Hanging Lights cable and anchor color in order to better match whatever I'm hanging it against. Maybe click a dye on the cable or anchor to change its color?

**Comment by pau101** [comment]
This is a feature which I would like to add.

**Comment by pau101** [comment]
[Fairy Lights 3.0.0](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2995387) now adds the option to have a white wire.
