### ISSUE TITLE
1.12 Players can destroy and modify light in regions (GriefPrevention)

### ISSUE THREAD

**Issue by SkyFire55** [pau101/Fairy-Lights#32]
When player right-clicks on central part of light (rope), he ignores all region flags including right and left-clicking, and destroys light. Is it fixable?

spongeforge-1.12.2-2555-7.0.0-BETA-2774.jar

**Comment by pau101** [comment]
Yes I can add support for this.

**Comment by pau101** [comment]
[Fairy Lights 2.1.2-1.12.x](https://minecraft.curseforge.com/projects/fairy-lights/files/2513426) has been released to resolve this issue.

**Comment by SkyFire55** [comment]
It works, thank you! Now I can close this issue.
