### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Matthysse** [pau101/Fairy-Lights#34]
Hello, yes the 1.7.10 version isn't updated, but i asked to the creator of Optifine, and he founded the problem but said that you can change that: Here is the issue: https://github.com/sp614x/optifine/issues/1121

So PLEASE just fix this problem, just this PLEASE!

**Comment by pau101** [comment]
I no longer support Minecraft 1.7.10 releases of Fairy Lights, you can however use Optifine version D6, as it is the last version which was compatible.
