### ISSUE TITLE
Null Pointer exception crash

### ISSUE THREAD

**Issue by ternsip** [pau101/Fairy-Lights#36]
Null Pointer exception  from https://github.com/pau101/Fairy-Lights/blob/c2d5657a95617283146df2bce363de9fab742e76/src/main/java/com/pau101/fairylights/client/ClientEventHandler.java#L182
trying to call [that](https://github.com/rwtema/Extra-Utilities-2-Source/blob/fccddf58116aa2ee11ece9aa2f9d1edb9a0d14b4/1.10.2/src/main/java/com/rwtema/extrautils2/transfernodes/TileTransferHolder.java#L231), but blockEntity is null (but in version 1.12.2)
https://pastebin.com/kysZzCzG
https://github.com/rwtema/Extra-Utilities-2-Source/issues/50#issuecomment-373966189
That happened on linux ubuntu to one of the players

**Comment by ternsip** [comment]
There is probability that one client mod was excessive surplus, and not existed on the server.

**Comment by pau101** [comment]
Thanks for reporting! Sorry for the very late reply, but I'll look into this.

**Comment by pau101** [comment]
So this bug did exist in EU2, but is fixed, rwtema/Extra-Utilities-2-Source/issues/1
