### ISSUE TITLE
White Color is Blue

### ISSUE THREAD

**Issue by GrumpSupport** [pau101/Fairy-Lights#37]
No matter what I do, it seems that for me, all the white lights omit a blue light color. I'm unsure if this is a glitch or if there is something else that is effecting the color of the lights, but I can't seem to find a work around.

![2018-04-21_10 50 43](https://user-images.githubusercontent.com/38581898/39082346-ed87654a-4551-11e8-9cfc-1b685992e878.png)

**Comment by AtomicWaffle14** [comment]
It seems like in the process of placing them they are white, but once placed they turn to a light blue color.

**Comment by pau101** [comment]
A new release will be out soon to resolve this.

**Comment by pau101** [comment]
[Fairy Lights 2.1.5](https://minecraft.curseforge.com/projects/fairy-lights/files/2645366) is now out to resolve this issue.
