### ISSUE TITLE
(incompatibility?) Issues with Cyclic

### ISSUE THREAD

**Issue by turret001** [pau101/Fairy-Lights#39]
Crash log
https://paste.dimdev.org/zujeguqoke.mccrash

Minecraft Version:
1.12.2

Mod Version:
2.1.2

I have posted the issue to Cyclic github aswell.
https://github.com/PrinceOfAmber/Cyclic/issues/841

**Comment by pau101** [comment]
Thanks for the report! This appears to be a repeat crash of #36

**Comment by pau101** [comment]
Yeah, this is just the same bug in two different mods.
