### ISSUE TITLE
Can't place anything but Tinsel Garlands/Letter Bunting/Vine Garland.

### ISSUE THREAD

**Issue by CelticChristoph** [pau101/Fairy-Lights#4]
Minecraft version: 1.10.2
Forge version: forge-12.18.3.2185
Fairylights version: fairlights-2.0.0-1.10.2

I've been playing around with the mod, and I am unable to place any of the lanterns. I've tried many different lantern types, as well as colors, and I am unable to place any of the lantern blocks themselves.

I am able to place the different garland blocks, but that is it.

Any ideas, or information I can provide? Would really love to get this mod working!

**Comment by pau101** [comment]
The lights aren't placeable, they are used to craft a strand of hanging lights.
Here are some example recipes:

![recipes](http://i.imgur.com/GcbQI0D.png)

**Comment by CelticChristoph** [comment]
Oh wow, I feel like such an idiot!
Thank you for the clear and clean reply!

Love the mod. =]
