### ISSUE TITLE
Z-Fighting When Connected Along A Fence

### ISSUE THREAD

**Issue by ChloeDawn** [pau101/Fairy-Lights#40]
The fairy lights will z-fight with the vanilla fence model's connection elements when connected through it in parallel and the camera is far enough away for depth inprecision to occur.

**Mod version:** [2.1.2-1.12.x](https://minecraft.curseforge.com/projects/fairy-lights/files/2513426)
**Forge version:** [1.12.2-14.23.4.2744](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2744/forge-1.12.2-14.23.4.2744-changelog.txt)

![screenshot](https://i.imgur.com/lGQlcno.png)

**Comment by InsomniaKitten** [comment]
I also notice a rendering issue regarding the translucency against the fluid renderer, although I believe that to be an issue with vanilla and not this mod. I can open a ticket for it regardless, if you want.

**Comment by pau101** [comment]
Closing as by design no restrictions are imposed on strand positioning and as such there are endless z-fighting chances.
