### ISSUE TITLE
Check For Space Before Allowing A Connection

### ISSUE THREAD

**Issue by ChloeDawn** [pau101/Fairy-Lights#41]
Currently, fasteners can be connected in a way that they intersect with other existing fairy lights. This can result in z-fighting and an unnatural appearance. Maybe you could have checks to ensure the to-be-placed fairy lights will not collide with existing ones?

**Mod version:** [2.1.2-1.12.x](https://minecraft.curseforge.com/projects/fairy-lights/files/2513426)
**Forge version:** [1.12.2-14.23.4.2744](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2744/forge-1.12.2-14.23.4.2744-changelog.txt)

![screenshot](https://i.imgur.com/ZHk2Y06.png)

**Comment by InsomniaKitten** [comment]
On a similar note, these suggested checks could also be applied to actual world collisions, to disallow connection of fasteners through solid blocks. Realistically, this would be an impossible connection, and makes no sense for fairy lights to be able to "phase through" an obstruction to meet their destination. 

![screenshot](https://i.imgur.com/FnMLeqD.png)
