### ISSUE TITLE
Fairy Lights Seem To Be Replaced By Identical Lights

### ISSUE THREAD

**Issue by ChloeDawn** [pau101/Fairy-Lights#45]
When interacting with an `ItemStack` of fairy lights identical to the ones being looked at in-world, the mod still attempts to "replace" them, and plays the replacement sound. This occurs in both survival and creative mode. A recording of the issue has been uploaded [here](https://streamable.com/hr3xs), where the sound is played each time the fairy lights are right-clicked.

**Mod version:** [2.1.2-1.12.x](https://minecraft.curseforge.com/projects/fairy-lights/files/2513426)
**Forge version:** [1.12.2-14.23.4.2744](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2744/forge-1.12.2-14.23.4.2744-changelog.txt)

**Comment by pau101** [comment]
Finally got around to this.
