### ISSUE TITLE
May cause lag

### ISSUE THREAD

**Issue by Mugiwaxar** [pau101/Fairy-Lights#47]
Hello,
Event subscribers of your mod can make server lag, it use a great amount of ressources
Here you can see:
![screenshot](https://user-images.githubusercontent.com/4124999/45220799-b1fd7980-b2af-11e8-980b-5838a5e39ac0.png)

I realy want to use this mod but I can not use it on my server for that reason ...
Please take a look !

**Comment by pau101** [comment]
Thanks for the report! I've put out a new [fairy lights release](https://minecraft.curseforge.com/projects/fairy-lights/files/2614275) which I had been planning on to, that addresses this.

**Comment by Mugiwaxar** [comment]
Ok, this is a good things
Thanks
