### ISSUE TITLE
Issue between Fairy Lights and Sponge

### ISSUE THREAD

**Issue by PoroUsedSnax** [pau101/Fairy-Lights#48]
So, this may seem like an odd one to report, not sure if it's one you're aware of also, but there is an issue over at sponge: SpongePowered/SpongeForge#2355 regarding cross-dimension teleporting. 

I was having this issue and Fairy Lights is mentioned in the Phase tracker error, so I tried deleting it to see if that would help, which it did, all is working fine. Which brings me to reporting it here, maybe there is something that can be fixed here to help with the issue?

**Comment by pau101** [comment]
Thanks for the report! I wasn't familiar with that issue, but after checking that out it does appear to be sponge which would need to implement a solution, you an see multiple mods reported producing this same incompatibility. There's nothing I can do on my end unfortunately, (aside from hacking into sponge to work around the issue or a nonfunctional stepladder, which I won't do).

**Comment by PoroUsedSnax** [comment]
Understandable, I appreciate the quick reply anyways!
