### ISSUE TITLE
[2.1.4] NPE ticking block entity

### ISSUE THREAD

**Issue by kreezxil** [pau101/Fairy-Lights#49]
I know I don't have to give you this many crash reports for a dedicated server. It's just to show you how badly fairy lights apparently crashed under forge build 2762.

The time stamps of the following (http://paste.ubuntu.com/p/qPbWBQgsBF/)

http://paste.ubuntu.com/p/sNZHK5KQTm/
http://paste.ubuntu.com/p/PcPCkKWBn3/
http://paste.ubuntu.com/p/jRN64rrsyg/
http://paste.ubuntu.com/p/QdDHRzJYWn/
http://paste.ubuntu.com/p/Vj534nYJkM/
http://paste.ubuntu.com/p/zytydRwsWq/
http://paste.ubuntu.com/p/X3hyXSMwsZ/
http://paste.ubuntu.com/p/Vhc7MnTWBt/
http://paste.ubuntu.com/p/V75r9ndmXV/
http://paste.ubuntu.com/p/9fNkcFqsFY/
http://paste.ubuntu.com/p/7zpTd7sy96/
http://paste.ubuntu.com/p/GXzgVFwXS9/
http://paste.ubuntu.com/p/x5GSwxjbV4/
http://paste.ubuntu.com/p/svwBP6rktG/
http://paste.ubuntu.com/p/Yr24d6zyDb/
http://paste.ubuntu.com/p/mSCgTxn7hQ/
http://paste.ubuntu.com/p/SGbyh22Tv5/
http://paste.ubuntu.com/p/6N4PvQYmh6/
http://paste.ubuntu.com/p/m98Z2rG2nw/
http://paste.ubuntu.com/p/YfCmXJTMcq/
http://paste.ubuntu.com/p/3Vv8VhDCBc/
http://paste.ubuntu.com/p/N5vN2zzDcj/
http://paste.ubuntu.com/p/zT3xHZbKtJ/
http://paste.ubuntu.com/p/GWxByHf2KF/
http://paste.ubuntu.com/p/nhjR9DrqQd/
http://paste.ubuntu.com/p/YCMG4dcW9V/
http://paste.ubuntu.com/p/KjD93GkZdc/
http://paste.ubuntu.com/p/9SzYXjX3QV/
http://paste.ubuntu.com/p/CMpjnqwGwW/
http://paste.ubuntu.com/p/qqv8rVgGY7/
http://paste.ubuntu.com/p/T5tnZbXxkS/

**Comment by kreezxil** [comment]
silly me just realized I never updated the server build 2762, but then this shouldn't have happened either right since you haven't updated in quite awhile.

**Comment by pau101** [comment]
When did you first experience this crash? Was it after a restart?

**Comment by kreezxil** [comment]
I did not personally experience. However in the words of one of my players.
It happened immediately when they broke one end of the fair lights. The
server immediately crashed. And since my server is always contained in a
reboot wrapper it generated a whole lot of crashes immediately because the
item broken was at spawn.

**Comment by pau101** [comment]
Could you provide the save file that results in the crash?

**Comment by kreezxil** [comment]
My bad, it's for a dedicated server. The world file is 25GB in size so i'm sure you don't want it. I don't have a copy of the region file where the bug is as I have edited it already and reuploaded it.

**Comment by pau101** [comment]
Ah, and there wouldn't happen to be a backup?

**Comment by kreezxil** [comment]
Nope, there is currently not a backup. I'll ask the guys to break the fairy lights again to see if we can duplicate it and then get that world file to you.
