### ISSUE TITLE
Crash between this mod and various oddities

### ISSUE THREAD

**Issue by Sunconure11** [pau101/Fairy-Lights#50]
https://paste.dimdev.org/hezimumowo.mccrash

https://minecraft.curseforge.com/projects/various-oddities

**Comment by pau101** [comment]
Thanks for the report! I've looked into this issue and it appears you'll have to report this to Various Oddities, as the mimic chest has an erroneous implementation. You can see this crash without Fairy Lights from trying to open a mimic chest with just Charsets installed as well.

**Comment by Sunconure11** [comment]
Dev has fixed this.
