### ISSUE TITLE
[Feature Request] Realistic flame and incandescent colours

### ISSUE THREAD

**Issue by Routhinator** [pau101/Fairy-Lights#53]
Ok, really loving this mod and the effort you put into the models. 

My one wish is to have a 'real' colour for each of the lanterns etc. So like for bulbs an incadescent bulb colour (sort of an off yellow/white) and for lanterns a flame colour (orange-yellow) that looks a little more realistic than the primary colours the mod sports now. The texture should have a little more intensity (similar to project reds lights, but not quite so bright).

**Comment by pau101** [comment]
[Fairy Lights 3.0.0](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2995387) now adds Incandescent, Candle, and Oil Lanterns.
