### ISSUE TITLE
World for HitConnection entity is null (not allowed by Forge)

### ISSUE THREAD

**Issue by whizzball1** [pau101/Fairy-Lights#54]
Hello!

My mod, Apathetic Mobs, is currently crashing in conjunction with your mod. This is because my mod checks all entities during AttachCapabilitiesEvent<Entity> and has to check if the entity is on the server. This means I must check `!e.getObject().getEntityWorld().isRemote`. When your entity, HitConnection, runs through my function, I assume getEntityWorld() is not null, because the documentation for getEntityWorld() says that it should never return null.

In order to fix this, Forge says that you should use the overworld if your entity is not in any world. Meanwhile, I can fix this on my end by checking `instanceof EntityLiving` before the world check (which I should have been doing all along, lol). But this could cause other problems in the future! So please fix it as soon as you can.

Thank you!

**Comment by pau101** [comment]
Thanks for the report! A new release will be out soon.

**Comment by pau101** [comment]
[Release 2.1.6](https://minecraft.curseforge.com/projects/fairy-lights/files/2703165) is now out!
