### ISSUE TITLE
Crash with Valkyrien Warfare

### ISSUE THREAD

**Issue by Melonslise** [pau101/Fairy-Lights#55]
I'm using Fairy Lights 2.1.6 and I've tried both [Valkyrien Warfare 0.9.5](https://minecraft.curseforge.com/projects/valkyrien-warfare/files/2570337) and their [latest beta build](https://jenkins.daporkchop.net/job/Valkyrien-Warfare-Revamped/415/). Whenever I try placing any kind of light on an existing ship or create a ship with a fairy light, the game completely freezes and crashes.

Crash report: https://pastebin.com/j2VZ9jwh

I don't know if it's on VW's side, but I do know that the mod handles ships in an unusual way: it stores them at the very edge of the map afaik.

Anyway I love both of these mods and hope the issue can be fixed soon. Thanks!

**Comment by pau101** [comment]
[Fairy Lights 2.1.7](https://minecraft.curseforge.com/projects/fairy-lights/files/2722013) now out to resolve this issue!
