### ISSUE TITLE
Crash upon teleporting to chunk with Fairy Lights placed

### ISSUE THREAD

**Issue by katubug** [pau101/Fairy-Lights#56]
Hi there! This past week, my players and I have started having some crashes that may be related to your mod. These have all happened on a multiplayer server and have caused the client to disconnect (but have not affected the server itself). The server logs haven't had anything unusual in them, and I do not have access to the client logs (but I'll try to get some).

I think in every case, the player that crashed has teleported to another player or a Waystone and crashed upon loading the chunk with the lights in it. Some have many lights, others have very few.

Crash reports:
https://pastebin.com/09j7gkb7
https://paste.dimdev.org/josazunuxo.mccrash
https://paste.dimdev.org/ekukucalev.mccrash

Versions:
fairylights-2.1.7-1.12.2
forge-1.12.2-14.23.5.2838-universal

My full modlist with versions is at the bottom of this post:
http://enthusiasticraft.cf/modpack-update-1-5-3/

**Comment by pau101** [comment]
Thanks for reporting! Patch will be available soon.

**Comment by katubug** [comment]
Great to hear, and happy to help. Thanks for the wonderful mod!

**Comment by katubug** [comment]
We've gotten another crash that doesn't seem to be the same, but may be related?

Here it is: https://paste.dimdev.org/ubupijikoc.mccrash

Let me know if you'd like me to make another issue for it. Thank you!

**Comment by pau101** [comment]
That is related yes! Just got it fixed as well as original issue in [Fairy Lights 2.1.9](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2738484)

**Comment by katubug** [comment]
Awesome, ty very much. We've been looking forward to it! :)
