### ISSUE TITLE
[Pasted] Another ValkyrienWarfare conflict

### ISSUE THREAD

**Issue by mappleaf** [pau101/Fairy-Lights#58]
https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/279

**Comment by pau101** [comment]
Thanks for the report! My integration with VW is for the last stable release and until a new stable release is out Fairy Lights will not be compatible.

**Comment by pau101** [comment]
Closing as no further updates to VW integration will occur for 1.12.
