### ISSUE TITLE
All Hangable Lights Won't Appear When Placed, Only The Ones Without Light

### ISSUE THREAD

**Issue by Cosmro** [pau101/Fairy-Lights#60]
Current Forge Version In-use: 14.23.5.2779
Current Mod Version In-use: fairylights-2.1.9-1.12.2

I was noticing a lot of the hangable fairy lights weren't being placed in the game, then I've realized only the ones without lights were able to be placed (vine, tinsel garland, pennant bunting, letter bunting), step-ladder works also. I've tried crafting it alone and going into creative mode. I have optifine though I use no shaders.

**Comment by pau101** [comment]
Thanks for reporting!

It sounds like you haven't crafted hanging lights. The lights themselves cannot be placed and instead are used to craft a light strand with a custom pattern like so:

![](http://i.imgur.com/GcbQI0D.png)

**Comment by Cosmro** [comment]
> Thanks for reporting!
> 
> It sounds like you haven't crafted hanging lights. The lights themselves cannot be placed and instead are used to craft a light strand with a custom pattern like so:
> 
> ![](https://camo.githubusercontent.com/ad13e70bdd513a15f8e7d217688b6a6ef923f31d/687474703a2f2f692e696d6775722e636f6d2f476362514930442e706e67)

Oh haha! Thank you for making it clearer for me. I was deeply confused so I apologize. Everything works properly.
