### ISSUE TITLE
Crash with the Ultimate Car Mod

### ISSUE THREAD

**Issue by WenXin20** [pau101/Fairy-Lights#62]
`Minecraft v1.14.4`
`Forge v28.1.104`
`Fairy Lights v2.1.10`
[`The Ultimate Car v2.0.21`](https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod)

With only Fair Lights and the Car mod installed, I get the following crash as soon as I try loading in a world. Without, the Ultimate Car mod, the world loads fine.
[Crash Report](https://gist.github.com/WenXin20/67af1a5b8726ef230fea1fbdbd3d99a4)

**Comment by pau101** [comment]
Thanks for reporting! A fix will be out soon.

**Comment by pau101** [comment]
[Fairy Lights 2.1.12](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842209) released.
