### ISSUE TITLE
Crashed when I died from lava fire damage

### ISSUE THREAD

**Issue by HonestAngel** [pau101/Fairy-Lights#63]
[crash-2019-12-13_03.37.25-client.txt](https://github.com/pau101/Fairy-Lights/files/3960575/crash-2019-12-13_03.37.25-client.txt)

**Comment by pau101** [comment]
Thanks for reporting! A patch will get released soon!

**Comment by pau101** [comment]
All resolved, [Fairy Lights 2.1.12](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842209)
