### ISSUE TITLE
the fairy lights sometimes stop rendering and then cause a crash when you break them. [1.14]

### ISSUE THREAD

**Issue by gravysamich** [pau101/Fairy-Lights#64]
[here is my crash log](https://pastebin.com/jQE1TBVc)

**Comment by pau101** [comment]
Thanks for reporting! Are they disappearing to response to anything you could see happen in game?

**Comment by pau101** [comment]
Okay I believe I got this resolved. [Fairy Lights 2.1.12](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842209)

**Comment by gravysamich** [comment]
excellent! 

it seems to be fixed

**Comment by RyanCR03** [comment]
:| it's still happening for me

**Comment by pau101** [comment]
@RyanCR03 Did you download 2.1.12? Please provide your crash report if so.

**Comment by RyanCR03** [comment]
I did, it doesn't crash for letter bunting but the rest crash the game with the message: The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: null

also, I used 2.1.13
