### ISSUE TITLE
1.14.4 - crash after editing Letter Bunting

### ISSUE THREAD

**Issue by Partonetrain** [pau101/Fairy-Lights#66]
After placing Letter Bunting and shift-clicking to edit, the letter amount seems to be 1 less than what it was when placing it. After clicking "Done", the game crashes with ArrayIndexOutOfBounds exception. 

Fairy Lights 2.1.12
Forge 28.1.106

https://pastebin.com/aubZBBWG

**Comment by pau101** [comment]
Thanks for reporting! A new release will be out soon.

**Comment by pau101** [comment]
[Fairy Lights 2.1.13](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842302) is now out!

**Comment by Partonetrain** [comment]
Thanks for the speedy fix!
