### ISSUE TITLE
breaking lights crash game

### ISSUE THREAD

**Issue by RyanCR03** [pau101/Fairy-Lights#67]
game crashes with the message: The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: null

Letter bunting doesn't crash the game

**Comment by pau101** [comment]
Could you please provide your crash report for me to further diagnose the issue.

**Comment by pau101** [comment]
Just released [2.1.14](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842784) to fix this.
