### ISSUE TITLE
Lag spike when turning lights on and off

### ISSUE THREAD

**Issue by zauberparacelsus** [pau101/Fairy-Lights#68]
With the hanging lights, I am noticing a lag spike when turning them on or off when the strand is very long.  With the debug stats enabled, it looks like activating the lights causes a surge of chunk updates.  Perhaps there is a more efficient way of handling this, such as breaking up the operation over multiple ticks?

**Comment by pau101** [comment]
Thanks for reporting! I imagine this is referring to the 1.12 version? I won't be providing any additional updates to that version unfortunately, with 1.14/1.15 being the priority now.
