### ISSUE TITLE
Recipes are broken w/ JEI & Botania

### ISSUE THREAD

**Issue by WenXin20** [pau101/Fairy-Lights#70]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Fairy Lights v2.1.14`

When viewing most Fairy Light Items with JEI, a blank recipe GUI will open up. An error is outputted to the log after pressing `r` to view a recipe.

EDIT: [Log](https://gist.github.com/WenXin20/a311cc3d6c790c2273f7f347c19aa4f7)

**Comment by pau101** [comment]
Thanks for reporting!

I am unable to reproduce. Do you have other mods installed?

**Comment by WenXin20** [comment]
Yes, about 100 other mods. 
If its a mod compat issue, I will have to try figure out which mod another day.

Did you try viewing the recipe from a Fairy Lights Item by finding it in JEI first?

**Comment by pau101** [comment]
Yes, I tried all the items as they appear in JEI and they work. I am not sure what compatibility issue could exist but having the list of mods would be helpful, or if you can try to narrow it down that would be great.

**Comment by WenXin20** [comment]
I'll try to send a screenshot of my mods soon. Maybe Crafttweaker affects the recipes?

**Comment by WenXin20** [comment]
Ok, I've found what causes this issue. Botania's Crafting Halos are probably what is causing the issue.
I'm using [`Botania r1.11-373`](https://www.curseforge.com/minecraft/mc-mods/botania)

**Comment by pau101** [comment]
Thanks, I am able to reproduce it now. I'll look into it.

**Comment by pau101** [comment]
I found the problem, each of Botania's floral powders are tagged as their according `forge:dyes/somedye`, but not in the top level `forge:dyes`. This causes my code expect a recipe using the Botania floral powders to work, but it doesn't. I can accept this unexpected state and allow the recipe to display, but this causes the recipe's dye ingredient to appear to support the Botania floral powders. However, it will not work in the crafting table. You will need to report this to Botania.

**Comment by pau101** [comment]
Actually, this appears to be a Forge bug, as the top level `forge:dyes` tag should reference the children dye tags.

**Comment by pau101** [comment]
They'll be a new Forge release to resolve this. https://github.com/MinecraftForge/MinecraftForge/commit/dbec9b3d5ac4c5e8545d960aebe1500329d64175

**Comment by WenXin20** [comment]
Awesome, thanks!

**Comment by pau101** [comment]
Forge 1.14.4-28.1.113 now resolves this.

**Comment by froggylovesu** [comment]
Hello. I play on 1.16.5, and the recipes are also, not working. It only works on the black variant of every light. But still, when using the black variant, it will not let me craft them. Am I doing something? And how can I resolve this?
