### ISSUE TITLE
Mod conflict between Refined Relocation and Fairy Lights

### ISSUE THREAD

**Issue by Howlingwolf1011** [pau101/Fairy-Lights#71]
On the public All The Mods 4 server, which uses both mods, i came across a instant game-breaking mod conflict.When using the "sorting interface" from Refined Relocation, and placing it facing into a "Sorting Chest" from the same mod, caused insta-disconnect, and disconnects anytime i try to log back in, when my GF logged in as well, it kicked her as well due to being in the same chunks i was. The bug report mentions "Fairy Lights" so we made a creative single player world with the mod pack and did the same steps, causing the same crash. We then tried removing Fairy Lights from the mod pack and loading it back up, which instantly fixed the issue.
[crash-2020-01-13_21.27.39-client.txt](https://github.com/pau101/Fairy-Lights/files/4059765/crash-2020-01-13_21.27.39-client.txt)

PS. ATM4 and Refined Relocation have both been made aware of this as well.

**Comment by blay09** [comment]
Bug is on Refined Relocation's side.

**Comment by pau101** [comment]
Thanks for reporting! But yep this does just appear to be on Refined Relocation's end.
