### ISSUE TITLE
Lights don't render when being hanged on any fence

### ISSUE THREAD

**Issue by Nika-m** [pau101/Fairy-Lights#72]
Actually I saw this issue already closed, THIS BUG IS FIXED IN [2.10.0](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2857644) but the problem is that 2.10.0 needs forge version at least 1.12.2 - 14.23.5.**2847**, as soon as Sponge is now supported on forge - 1.12.2 - 14.23.5.**2838**, I can't install fairylights 2.10.0 on Sponge server so bug is still alive,
Tried removing all other mods but it still happens, as it seems it has issue with forge version. if it could be fixed I would be happy, but ifnot don't worry too much maybe in some time sponge will update forge versions.

**Comment by pau101** [comment]
1.12 is no longer supported and Fairy Lights 2.10.0 is the final release for that version.
