### ISSUE TITLE
Crashes after downloading Fairy Lights

### ISSUE THREAD

**Issue by MapleSyrup07** [pau101/Fairy-Lights#73]
https://pastebin.com/DfDGXKGq
Not sure if this is caused by Fairy Lights but it started after downloading this mod. My game would randomly crash when opening a crafting bench or chest, although not every time. The crash report also mentions fairy lights a few times.

**Comment by pau101** [comment]
Thanks for reporting, however unfortunately 1.7.10 is very far out of support.
