### ISSUE TITLE
Issue: (1.12.2) Dissapearing letter bunting 

### ISSUE THREAD

**Issue by StitchXD** [pau101/Fairy-Lights#75]
![obraz](https://user-images.githubusercontent.com/67462933/85950176-93bcae00-b95b-11ea-9b6a-df6a889281ac.png)
Hello, i would like to report an issue that honestly is really annoying while building. Let's say that you are making a long fence, NOT  placing the vanilla fence, making a fence. It takes you about 15 mins, but finally youre done. You go somewhere else, to work on something and after 30 mins you return, and some of buntings are gone. This happens to me a lot honestly, and i will be very grateful if you could please fix that. ( btw im using version 2.1.10, which is the newest one for 1.12.2)
![2020-06-28 (5)](https://user-images.githubusercontent.com/67462933/85949610-104d8d80-b958-11ea-9719-96a8de361994.png)

**Comment by pau101** [comment]
Do they reappear if you leave and rejoin the world?

**Comment by StitchXD** [comment]
Yea, i think its just a texture glitch. But still rejoining the world everytime it happens doesn't have a lot of sense because as i mentioned, it happens a lot with this "fence". Also im sorry for not putting a lot of information, if you would like i could see if it is just a conflict with other mods, by making a world with fairy lights mod **only**.btw. The textures somtimes also appear when i click with letter bunting on the fence that currently invisible bunting is attached to. If you need any more information just ask, i will be more than happy to help :)

**Comment by pau101** [comment]
Okay good that is what I suspected and I know what change is needed.

**Comment by pau101** [comment]
[Fairy Lights 2.1.11](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2995382) is now out to resolve this.
