### ISSUE TITLE
JEI Error

### ISSUE THREAD

**Issue by WenXin20** [pau101/Fairy-Lights#78]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Fairy Lights v3.0.5`
`JEI v6.0.2.12`

If I press `u` to view the use for a light, JEI will instead throw an exception and show a blank gui instead.
[Error Log](https://gist.github.com/WenXin20/e3bad66ed53cc14f5ab65acf00dfd88d)

**Comment by pau101** [comment]
Thanks for reporting, I'll look into it!

**Comment by WenXin20** [comment]
Thanks!

**Comment by pau101** [comment]
I've fixed the problem in dev now. I new patch will be out within a few days.

**Comment by pau101** [comment]
[3.0.7](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3009348) is now out
