### ISSUE TITLE
Fairy lights 1.12 simply doesn't work

### ISSUE THREAD

**Issue by Ricket** [pau101/Fairy-Lights#80]
I added `fairylights-2.1.11-1.12.2` to Enigmatica 2 Expert (pack v 1.81a). Verified same version on client & server. We can craft the stepladder, and the lights, but cannot place any lights. Right-clicking with the lights onto a surface does nothing. Tested with various lights and various surfaces. (and I have used this mod successfully long ago so I know I am not doing something wrong)

I grepped through the logs and did not find any errors. I think next steps would be to test the mod alone in MultiMC with the same forge version (14.23.5.2847) to confirm it works, and if so then start adding mods binary-search style until we find the conflicting mod from the E2E modpack.

I'll try to do that sometime in the next few days but in the meantime wanted to go ahead and open this issue, in case it's known or someone else comes across this, or someone else wants to test it out for me.

**Comment by pau101** [comment]
The lights themselves are not placeable, they are used to craft hanging lights. As described on the mod page, here are some example usages:

![Example recipes](http://i.imgur.com/GcbQI0D.png)

**Comment by Ricket** [comment]
Thanks, that worked. It's abundantly clear in the mod description, I skimmed it instead of reading.

Definitely facepalm at my "I have used this mod successfully long ago so I know I am not doing something wrong" and I'm glad I didn't waste time "verifying" that it's still broken by itself...
