### ISSUE TITLE
1.15.5 Lights for 1.12.2?

### ISSUE THREAD

**Issue by Atenberus** [pau101/Fairy-Lights#81]
Hello sorry if I'm being annoying, but I was wondering if you were going to add the new light mechanics from 1.15.2 to 1.12.2, as a lot of people still play on it. I don't know anything about code so if it isn't possible or you're already planning on doing it just ignore me. (I don't know how to tag this as a suggestion so don't worry, the mods working fine on my computer)

**Comment by pau101** [comment]
I appreciate the interest in the new content however 1.12 is only receiving critical bug fixes.

New content is developed for the most up-to-date releases as those are where active development is and are what versions are supported by Forge. Also, with the 1.15 release in particular there was a major rewrite so it would require additional work to reimplement features. I hope you can understand.

**Comment by Atenberus** [comment]
Okie Dokie
