### ISSUE TITLE
Shaders glitch fairy lights

### ISSUE THREAD

**Issue by xVVitch** [pau101/Fairy-Lights#83]
When looking at fairy lights from a certain direction fairy lights glitch out when using sildur's vibrant medium shaders.

https://imgur.com/mPpGHKZ
https://imgur.com/DQYo9l2

**Comment by pau101** [comment]
Thanks for reporting! Can you recreate this using the "Light" version?

**Comment by pau101** [comment]
As there was only ever a pre release of OptiFine for 1.15, I'll close and potentially revisit when updating to 1.6
