### ISSUE TITLE
Incompatible with Futurepack Mod ?

### ISSUE THREAD

**Issue by Darianna77** [pau101/Fairy-Lights#84]
Hehe..

It seems tha this mod causes a game crash and broken world with Futerepack Dungeons. When i will try to port to an futurepack dungeon the Game crashes and then the world is broken because it crashes on every start. That are the Logs 👍 

The Crash log is here: https://pastebin.com/M4AzZ3Dm

thats the log when i try to restart the savegame: https://pastebin.com/FuqAzYd4

When i disable your Mod it works..but i like your mod  and would really play with both . Is that something that can fixed? The same Report is postet in FuturePack Mod

**Comment by pau101** [comment]
This is an issue with another mod's block that is in proximity to you, but I cannot know which with the crash alone. Can you list what blocks are around you?

**Comment by Darianna77** [comment]
That are all Blocks from the Futurepack Mod. Normal Blocks an yeah...lighting blocks that lights up when i near or step on it it seems. Maybe these lights are the crash-thing. I can give you the  names of the Blocks...do you know the Futurepack Mod? The Name from the Block that makes light when near /step up is Quantanium. Cannot tell you more because its a mod with  a lot of research that i havent done :)

**Comment by pau101** [comment]
Thank you, I should have the information to identity the problem.

**Comment by Darianna77** [comment]
I hope the little info from me can help. The other Blocks there are mostly normal Colored Metal Blocks. Its a biig structure :)

**Comment by pau101** [comment]
I have identified the issue in Futurepack Mod and you will need to follow up on them for a fix.
