### ISSUE TITLE
Crash due to missing MIDI mapper

### ISSUE THREAD

**Issue by Penguixia** [pau101/Fairy-Lights#85]
The mod sometimes crashes when exiting out of a singleplayer world due to a missing MIDI Mapper. I'm not sure exactly what causes this crash, but I have a MIDI mapper installed and it still sometimes crashes, unfortunately.
[Here's my crash log.](https://github.com/pau101/Fairy-Lights/files/5117511/crash-2020-08-24_07.39.48-client.txt)

**Comment by pau101** [comment]
Thanks for reporting! A fix will be on the way.

**Comment by pau101** [comment]
Resolved in [3.0.9](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3041074)

**Comment by Penguixia** [comment]
Thanks!
