### ISSUE TITLE
Client Crashes when teleporting to a chunk with Fairy Lights in it (1.15.2)

### ISSUE THREAD

**Issue by Purplo262** [pau101/Fairy-Lights#86]
Hi, I am using the Fairy Lights mod with a few other mods and I have had a few crashes which appear to be related to this mod.

Occassionally, when teleporting to a chunk with fairy lights in (either through waypoint teleports or waystones) In a multiplayer game, the client crashes. It's not a hard crash ( the game closes the world and saves then crashes)and it doesn't happen everytime I teleport.

Here is the crash log:
https://pastebin.pl/view/1761dd95

I also noticed a similar issues listed here #56 
But this was a while ago.

**Comment by pau101** [comment]
Thanks for reporting! I see this ocurred on 3.0.7, have you tried the latest patch 3.0.9?

**Comment by Purplo262** [comment]
I tried 3.0.9. , Worked fine for a bit but just had the same crash when teleporting with a Waystone. 
I can try 3.1.0. to see if the problem still occurs

**Comment by gjroelofs** [comment]
Same error, same stacktrace on 3.0.10.

**Comment by pau101** [comment]
Should be now fixed in [3.0.11](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3068509)
