### ISSUE TITLE
fairy lights issue with shaders (fairy lights emit light but look like they are shut off)

### ISSUE THREAD

**Issue by fachao** [pau101/Fairy-Lights#87]
When placing any kind of lights, they do emit light when on, but the individual bulbs/lanterns look like they are not on. I'm using BSL shaders and have this issue on both 1.12.2 and 1.14.4

Can be reproduced by placing any fairy lights while using BSL Shaders

![ser](https://user-images.githubusercontent.com/59300443/92310208-170d0800-ef7a-11ea-85fc-103c782c31c4.png)

**Comment by pau101** [comment]
I have seen this issue and the last version of BSL where they appear correctly in 1.14.4 is [BSL v7.1
](https://www.curseforge.com/minecraft/customization/bsl-shaders/files/2715250) This is an issue with the shader, nothing I can do.

**Comment by pau101** [comment]
I just tried later versions of the shaders not marked specifically for 1.14, ([7.2](https://www.curseforge.com/minecraft/customization/bsl-shaders/files/3037267)) and the lights do actually appear correct, so the issue appears resolved.
