### ISSUE TITLE
Crash with Ice and Fire

### ISSUE THREAD

**Issue by Penguixia** [pau101/Fairy-Lights#90]
I'm not sure if this is an issue on your end or Ice and Fire's end, but for some reason when placing a jar of any kind (from Ice and Fire), it causes a crash. I've opened up an issue on Ice and Fire just to cover all my bases.

[Link to issue on Ice and Fire's Repo](https://github.com/Alex-the-666/Ice_and_Fire/issues/2886)
[Ice and Fire's Repo](https://github.com/Alex-the-666/Ice_and_Fire)
[Crash log](https://github.com/pau101/Fairy-Lights/files/5298986/crash-2020-09-29_08.29.40-client.txt)

**Comment by pau101** [comment]
Thanks for reporting! Yep this is an issue on Ice and Fire's end, similar to other mods with same error, breaking capability contract by returning `null` instead of an empty `LazyOptional`.
