### ISSUE TITLE
Cannot place Fairy Lights in the Tropicraft Dimension.

### ISSUE THREAD

**Issue by Purplo262** [pau101/Fairy-Lights#91]
I'm unsure whether or not this is a problem on their end or here.

I'm using the latest version (3.0.11.) 1.15.2.

In the overworld, I can place hanging fairy lights normally, but in the Tropics dimension from the Tropicraft mod, whenever I click to place hanging lights it acts like I'm placing a new line. So I click once to start hanging, but the second starts another line, a third click starts another etc etc. I end up with a whole line of hanging lights following me and I cannot remove them unless I break the starting points.

This happens with all types of lights, creative and survival.

Let me know if a log is needed for this issue, but here's an image;
![2020-10-18_21 41 19](https://user-images.githubusercontent.com/61368657/96362567-b8e35f80-118a-11eb-8315-ffdf5f13c897.png)

**Comment by pau101** [comment]
Thanks for reporting!

I've reproduced the issue and it appears this occurs in all dimensions other than overworld. A fix will be under way.

**Comment by pau101** [comment]
Fairy Lights [3.0.12](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3086059) is now out to resolve this issue.
