### ISSUE TITLE
"Craft Hanging Lights" toast does not go away until crafted

### ISSUE THREAD

**Issue by Goldenlion5648** [pau101/Fairy-Lights#92]
After obtaining white tinsel garland (cheated in), a toast came up saying to craft hanging lights (the recipe book can help). The toast did not go away until I cheated in the hanging lights after a minute or two. 

I have a few mods disabling the recipe book if that could be affecting it.

**Comment by pau101** [comment]
This is by design, as it is a tutorial toast instructing how to obtain hanging lights. It appears after the player picks up a light item.

**Comment by Goldenlion5648** [comment]
Can this be a config? It is a little annoying for the toast to stay if someone gets a light item, but does not have the materials for hanging lights.

**Comment by pau101** [comment]
If the player does not have a light in their inventory it goes away. The tutorial state is stored in config so it can be edited, however I advise against a modpack disabling my tutorial as I recently added and designed it to help the many comments I get about new users having trouble using hanging lights.
