### ISSUE TITLE
World Lighting crash on /tp

### ISSUE THREAD

**Issue by CelestiaSalinas** [pau101/Fairy-Lights#93]
A frequent client crash on a server I admin points to fairy lights and world lighting when someone teleports

Here's the pastebin: https://pastebin.com/vQ88cZDE

Never opened an issue before, pls let me know if you need to see anything else.

**Comment by pau101** [comment]
Thanks for reporting! New release will be out soon.

**Comment by CelestiaSalinas** [comment]
Thank you so much!

**Comment by pau101** [comment]
[Fairy Lights 3.0.14](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3108314)

**Comment by CelestiaSalinas** [comment]
Sorry to bother you again, but it seems this crash still happens? has occurred twice now, that Im aware of

pastebin: https://pastebin.com/p6uM19zH

Please let me know if you need anything else, or if this may be the cause of a mod conflict, which I understand is not your responsibility

**Comment by pau101** [comment]
Oh I see, I assumed this was a server crash yet it is not. Are you able to reproduce this with only Fairy Lights installed?

**Comment by CelestiaSalinas** [comment]
Sorry for the late response
I isolated fairy lights on my server and tped around
Doesn't appear to happen anymore. I believe so, at least.
The crash isn't on every tp, but it's often enough to be troublesome

Im guessing this means it's likely a mod conflict?

**Comment by pau101** [comment]
Does it occur with OptiFine and Fairy Lights?

**Comment by CelestiaSalinas** [comment]
Doesn't appear so, no. I tested it with fairy lights, optifine, and invisiblights as well, in case the only other lighting mod could be the case. But, no dice.

**Comment by lulabyte** [comment]
Just wanted to say I also have this issue on our server, but I think I'm crashing client side? 1.16.3

I have Optifine installed for the record, but also a bunch of other mods haha.

Let me get the log.

**Comment by pau101** [comment]
Could you try installing this [version](https://drive.google.com/file/d/1hzna9fpOURQxB_SEXuw9qw-TsPM7vcCr/view?usp=sharing) and check if issue persists?

**Comment by lulabyte** [comment]
(Will that work for 1.16.3?)

**Comment by pau101** [comment]
No I just made a 1.15 build

**Comment by pau101** [comment]
Okay [here](https://drive.google.com/file/d/1HJ244NV5y8gFgz2P1LrXKr5L0pztHKNf/view?usp=sharing) is the attempted fix for 1.16 to test @lulabyte

**Comment by CelestiaSalinas** [comment]
Ah, sorry I missed this update! It seems this has indeed fixed the crash :D Tysm!

**Comment by pau101** [comment]
Now resolved in [3.0.15-1.15.2](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3134277) and [4.0.3-1.16.4](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3134283).
